#
# Copyright 2022 isobar. All Rights Reserved.
#
# The isobar node image with ffmpeg
#

FROM isobar/node:16-alpine-gm-ffmpeg
LABEL maintainer "jacky.huang@isobar.com"

RUN apk --no-cache add imagemagick
