#
# Copyright 2022 isobar. All Rights Reserved.
#
# The isobar node image with ffmpeg(tag: node-12-alpine-gm-ffmpeg-im-pm2)
#

FROM isobar/node:12-alpine-gm-ffmpeg-im
LABEL maintainer "jacky.huang@isobar.com"

WORKDIR /workspace

RUN npm install pm2 -g

COPY ./sh/docker-yarn-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["docker-yarn-entrypoint.sh"]

# Define default command.
CMD ["pm2-runtime", "start", "pm2.json"]
