#
# Copyright 2020 isobar. All Rights Reserved.
#
# The isobar node image(From alpine:3.11)
#

FROM node:12-alpine
LABEL maintainer "jacky.huang@isobar.com"

WORKDIR /workspace

# install dev tools
RUN apk --no-cache add curl git openssl subversion

# Define default command.
CMD ["node", "-v"]
