#
# Copyright 2022 isobar. All Rights Reserved.
#
# The isobar node image with ffmpeg(tag: node-12-alpine-ffmpeg)
#

FROM isobar/node:12-alpine
LABEL maintainer "jacky.huang@isobar.com"

RUN apk --no-cache add ffmpeg
