#
# Copyright 2019 isobar. All Rights Reserved.
#
# The isobar node image(From alpine:3.10)
#
# Usage:
#       dk build -t isobar/node-8:1.0.0 -f Dockerfile .
#
FROM node:12-alpine
LABEL maintainer "jacky.huang@isobar.com"

RUN apk --no-cache add curl git openssl libpng librsvg libgsf giflib libjpeg-turbo musl && \
    npm install pm2 -g

# Define default command.
CMD ["pm2-runtime", "-V"]
